### ISSUE TITLE
Licensing compliance

### ISSUE THREAD

**Issue by fabrizioschiavi** [xpando/Dash#3]
PragmataPro is not free software and I, the author, haven’t ever made it available in a particularly permissive form. Also worth noting - you appear to have an older (buggy) version of PragmataPro which is missing certain ligatures added in 0.820.
http://www.fsd.it/fonts/pragmatapro.htm
http://www.fsd.it/fonts/eula.htm

**Comment by alexbooker** [comment]
If the author does not respond to your pull request soon, you could always issue a [DMCA notice](https://help.github.com/articles/dmca-takedown-policy/).

Removing the files alone will likely remove them from search engines however, they will still be accessible in the Git history. I *suspect* GitHub would purge the files entirely if you got in touch with them.

**Comment by xpando** [comment]
I didn't mean to commit these. The files have been permanently deleted from the repository,
